package com.springboot.demo.mapper;

import com.springboot.demo.model.Dormitory1;
import com.springboot.demo.model.Dormitory1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Dormitory1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    long countByExample(Dormitory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int deleteByExample(Dormitory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int insert(Dormitory1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int insertSelective(Dormitory1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    List<Dormitory1> selectByExampleWithRowbounds(Dormitory1Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    List<Dormitory1> selectByExample(Dormitory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    Dormitory1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dormitory1 record, @Param("example") Dormitory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByExample(@Param("record") Dormitory1 record, @Param("example") Dormitory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(Dormitory1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory1
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByPrimaryKey(Dormitory1 record);
}