package com.springboot.demo.mapper;

import com.springboot.demo.model.Nodee;
import com.springboot.demo.model.NodeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NodeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    long countByExample(NodeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int deleteByExample(NodeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int insert(Nodee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int insertSelective(Nodee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    List<Nodee> selectByExampleWithRowbounds(NodeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    List<Nodee> selectByExample(NodeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    Nodee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Nodee record, @Param("example") NodeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByExample(@Param("record") Nodee record, @Param("example") NodeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(Nodee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodee
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    int updateByPrimaryKey(Nodee record);
}