package com.springboot.demo.mapper;

import com.springboot.demo.model.Persons;
import com.springboot.demo.model.PersonsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PersonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    long countByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int deleteByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int insert(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int insertSelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    List<Persons> selectByExampleWithBLOBsWithRowbounds(PersonsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    List<Persons> selectByExampleWithBLOBs(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    List<Persons> selectByExampleWithRowbounds(PersonsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    List<Persons> selectByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    Persons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int updateByExample(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int updateByPrimaryKeySelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Fri May 01 23:04:45 CST 2020
     */
    int updateByPrimaryKey(Persons record);
}