package com.springboot.demo.model;

import java.util.Date;

public class Dormitory1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.Id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.seller
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String seller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.buyer
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.content
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.amount
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.unitprice
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Integer unitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.sum
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Integer sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory1.time
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.Id
     *
     * @return the value of dormitory1.Id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.Id
     *
     * @param id the value for dormitory1.Id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.seller
     *
     * @return the value of dormitory1.seller
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.seller
     *
     * @param seller the value for dormitory1.seller
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setSeller(String seller) {
        this.seller = seller == null ? null : seller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.buyer
     *
     * @return the value of dormitory1.buyer
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.buyer
     *
     * @param buyer the value for dormitory1.buyer
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.content
     *
     * @return the value of dormitory1.content
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.content
     *
     * @param content the value for dormitory1.content
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.amount
     *
     * @return the value of dormitory1.amount
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.amount
     *
     * @param amount the value for dormitory1.amount
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.unitprice
     *
     * @return the value of dormitory1.unitprice
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Integer getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.unitprice
     *
     * @param unitprice the value for dormitory1.unitprice
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setUnitprice(Integer unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.sum
     *
     * @return the value of dormitory1.sum
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.sum
     *
     * @param sum the value for dormitory1.sum
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory1.time
     *
     * @return the value of dormitory1.time
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory1.time
     *
     * @param time the value for dormitory1.time
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}