package com.springboot.demo.model;

public class Node {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.id
     *
     * @return the value of node.id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.id
     *
     * @param id the value for node.id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}