package com.springboot.demo.model;

import java.util.Date;

public class Persons {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.create_datetime
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.email
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.phone
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.sex
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.username
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.zone
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    private byte[] zone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.id
     *
     * @return the value of persons.id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.id
     *
     * @param id the value for persons.id
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.create_datetime
     *
     * @return the value of persons.create_datetime
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.create_datetime
     *
     * @param createDatetime the value for persons.create_datetime
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.email
     *
     * @return the value of persons.email
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.email
     *
     * @param email the value for persons.email
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.phone
     *
     * @return the value of persons.phone
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.phone
     *
     * @param phone the value for persons.phone
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.sex
     *
     * @return the value of persons.sex
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.sex
     *
     * @param sex the value for persons.sex
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.username
     *
     * @return the value of persons.username
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.username
     *
     * @param username the value for persons.username
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.zone
     *
     * @return the value of persons.zone
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public byte[] getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.zone
     *
     * @param zone the value for persons.zone
     *
     * @mbg.generated Wed May 13 15:22:44 CST 2020
     */
    public void setZone(byte[] zone) {
        this.zone = zone;
    }
}